chat/urls.py
from django.conf.urls.defaults import patterns, url
from views import home,message,create_chat,retrieve_chat,retrieve_message,delete_chat


urlpatterns = patterns('',
    #url(r'^login/$', auth_views.login,{'template_name': 'registration/login.html'},name='auth_login'),    #URL TO LOGIN
    #url(r'^logout/$',auth_views.logout,{'template_name': 'registration/logout.html'},name='auth_logout'), #URL TO LOGOUT VIA AUTH
    url(r'^$',
        home,
        name='home'),
    url(r'^m/$',
        message,
        name='message'),                    #URL TO STEP 1 OF USER REGISTER    
     url(r'^create_chat/$',
        create_chat,
        name='create_chat'),
    url(r'^retrieve_chat/$',
        retrieve_chat,
        name='retrieve_chat'),
    url(r'^retrieve_message/$',
        retrieve_message,
        name='retrieve_message'),
    url(r'del_chat/$',
        delete_chat,
        name="delete_chat"),                #URL TO DELETE A GIVEN CHAT               
)

share_economy/urls.py
from django.conf.urls import patterns, include, url
from user.views import index, tos

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^actualizar/', 'user_profile.views.user_update_view'),
    ('^$', index),
    ('^home/$', index),
    ('^tos/$',tos),
    (r'^notifications/', include('notifications.urls')),
    (r'^comments/', include('comments.urls')),
    (r'^account/', include('user.urls')),
    (r'^product/', include('product.urls')),
    (r'^stream/', include('feedStream.urls')),
    (r'^group/', include('group.urls')),
    (r'^offer/', include('offer.urls')),
    (r'^auth/', include('facebook.urls')),
    (r'^chat/', include('chat.urls')),
    (r'^updates/', include('errorReport.urls')),

)

user/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from views import *
from forms import PasswordResetForm

urlpatterns = patterns('',
    url(r'^register/(?P<user_id>\w+)/$',
        register,
        name='registration_register'),
    url(r'^register/$',
        register,
        name='registration_register'),                    #URL TO STEP 1 OF USER REGISTER
    url(r'^register_trust/(?P<edit>\w+)/$',
        register_step_2,
        name='registration_register_step_2'), 
    url(r'^register_trust/$',
        register_step_2,
        name='registration_register_step_2'),            #URL TO STEP 2 OF USER REGISTER
    url(r'^register_comun/(?P<user_id>\w+)/$',
        registration_register_step_3,
        name='registration_register_step_3'),
    url(r'^register_comun/',
        registration_register_step_3,
        name='registration_register_step_3'),           #URL TO STEP 3 OF USER REGISTER
    url(r'^register/complete/$',
        RedirectView,
        {'template': 'registration_complete.html'},     #URL TO REGISTRATION COMPLETE
        name='registration_complete'),
    url(r'^activate/(?P<activation_key>\w+)/$',
        activate,
        name='registration_activate'),                  #URL TO ACTIVATE AN ACCOUNT
    url(r'^login/',
        login_view,
        name='kamvia_login'),                           #URL TO LOGIN VIA Kamvia
    url(r'^profile/$',
        user_profile,
        name='admin_profile'),                           #URL TO USER PROFILE 
    url(r'^profile/(?P<user_id>\w+)/$',
        user_profile,
        name='user_profile'),                           #URL TO USER PROFILE 
    url(r'^$',index,name='index'),
    url(r'^picture/', regist_prof_pic, name='picture_upload'), #Upload picture to s3
    url(r'^home/', home, name='home_inicio'),
    url(r'^logout/',user_logout,name='logout'),
    url(r'^friend_request/',send_friend_request,name='send_friend_request'),
    url(r'^resp_friend_request/', response_friend_request,name='response_friend_request'),
    url(r'^wishlist/$',wish_form,name='wish_form'),
    url(r'^add_wish/',add_wish,name='add_wish'),
    url(r'^get_wishlist/$',get_wishlist,name="get_wishlist"),
    url(r'^get_wishlist/(?P<user_id>\w+)/$',get_wishlist,name="get_wishlist_user"), 
    url(r'^user_friends/(?P<user>\w+)/$',user_friends,name='user_friends'),
    url(r'^list_user_friends/$',user_friend_json,name='user_friend_json'),
    url(r'^search_friend/$', search_friend, name='search_friend'),
    url(r'^csv/',reader_csv,name='token'),
    url(r'^token_activate/(?P<token>\w+)/$',token_activate,name='token_activate'),
    url(r'^wishes/$',wish_follow_all,name='home_whises'),
    url(r'^edit/$',register,name='edit_register'),
    url(r'^mail/$',webmail,name='edit_register'),
    url(r'^error/$',error_report,name='edit_register'),
    url(r'^retrive_password/$',email_reset_password,name='reset_password'),
    url(r'^recupera_contra/(?P<salt>\w+)/$',new_password,name='new_password'),
    url(r'^change_pass',new_password,name='new_password_sn_salt'),
    url(r'^search_result/$',search,name='search'),           #URL TO RENDER TE RESULTS PAGE 
    url(r'^search_user/$',find_users,name='find_users'),
    url(r'^checkdata/$',check_popup,name='check_popup'), 
)

user/models.py
from documents import *

user/forms.py
#!/usr/bin/python
# vim: set fileencoding= utf-8 :
"""
Forms and validation code for user registration.

"""


from django import forms
from django.contrib.auth.forms import PasswordResetForm as AuthPRF
from django.contrib.auth.hashers import UNUSABLE_PASSWORD
from django.utils.translation import ugettext_lazy as _
from mongoengine.django.auth import User
from models import *
from documents import RegistrationProfile, Address

import re


# I put this on all required fields, because it's easier to pick up
# on them with CSS or JavaScript if they have a class of "required"
# in the HTML. Your mileage may vary. If/when Django ticket #3515
# lands in trunk, this will no longer be necessary.
attrs_dict = {'class': 'required'}


class RegistrationForm(forms.Form):
    """
    Form for registering a new user account.

    """
    name = forms.CharField( max_length=30,
                            widget=forms.TextInput(attrs={'ng-model':'user.first_name','placeholder':'Escribe tu nombre', 'class':'left required bg-gray', 'data-type':'text'}),
                            label=_(u'El nombre que usaremos para correos electronicos'),
                            error_messages={'required': 'Campo requerdo'}
                            )
    username = forms.CharField(max_length=30,
                                widget=forms.TextInput(attrs={'ng-model':'user.username','placeholder':'Nombre de usuario', 'class':'left required bg-gray', 'data-type':'text'}),
                                label=_(u'Nombre de usuario'),
                                required=False
                                )
    user = forms.CharField(widget=forms.HiddenInput(attrs={'value':''}),required=False)
    email = forms.EmailField(widget=forms.TextInput(attrs=dict({'ng-model':'user.email','placeholder':'tu correo', 'class':'left required bg-gray', 'data-type':'email'},
                                                               maxlength=75)),
                             label=_(u'Correo'),
                             required=False
                             )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'ng-model':'user.password1','placeholder':'una contraseña', 'class':'left required bg-gray', 'data-type':'password'}, render_value=False),
        label=_(u'Contraseña'),
        required=False
        )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'ng-model':'user.password2','placeholder':'confirma tu contraseña', 'class':'left required bg-gray', 'data-type':'repeat_password'}, render_value=False),
        label=_(u'Contraseña (repetir)'),
        required=False
        )
    stp1_id = forms.CharField(widget=forms.HiddenInput(attrs={'ng-model':'form_id','value':'{[form_id="form_id_11"]}'}),required=False)
    nxt_stp_id = forms.CharField(widget=forms.HiddenInput(attrs={'ng-model':'kamvia_next_id', 'value':'{[kamvia_next_id]}'}),required=False)

    tos = forms.BooleanField()

    def clean(self):
        user_id = self.cleaned_data.get('user')
        if user_id != '':
            user = RegistrationProfile.objects(id=user_id).first()
            if user.username != self.cleaned_data['username']:
                if RegistrationProfile.objects(
                    username__iexact=self.cleaned_data['username']):
                    print "Este nombre de usuario ya ha sido tomado por un usuario."
                    raise forms.ValidationError(
                        _(u'Este nombre de usuario ya ha sido tomado por un usuario.'))
        else:
            if RegistrationProfile.objects(
                username__iexact=self.cleaned_data['username']):
                print "Este nombre de usuario ya ha sido tomado por un usuario."
                raise forms.ValidationError(
                    _(u'Este nombre de usuario ya ha sido tomado por un usuario.'))

        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """

        if user_id == '':
            print "tooooos"
            tos = self.cleaned_data.get('tos')
            name = self.cleaned_data.get('name')
            username = self.cleaned_data.get('username')
            email = self.cleaned_data.get('email')
            password1 = self.cleaned_data.get('password1')
            password2 = self.cleaned_data.get('password2')
            if tos is not True:
                print "Debes aceptar los terminos y condiciones."
                raise forms.ValidationError(_(u'Debes aceptar los terminos y condiciones.'))
            if password1 != password2:
                print "Las contraseñas no son iguales."
                raise forms.ValidationError(
                    _(u'Las contraseñas no son iguales.'))

            if len(password1)<8:
                print "La contraseña debe contener almenos 8 caracteres."
                raise forms.ValidationError(
                    _(u'La contraseña debe contener almenos 8 caracteres.'))

            if password1==None or password2 ==None or email==None or username==None or name==None :
                print "Todos los campos son necesarios"
                raise forms.ValidationError(
                    _(u'Todos los campos son necesarios'))
        """
        Verifiy that the email entered is not duplicated
        for register user and for a new user
        user_id = '' new user
        """

        user_id = self.cleaned_data.get('user')
        if user_id == '':
            if RegistrationProfile.objects(
                email__iexact=self.cleaned_data['email']):
                print "Ya existe una cuenta con ese email."
                raise forms.ValidationError(
                    _(u'Ya existe una cuenta con ese email.'))
        else:
            user = RegistrationProfile.objects(id=user_id).first()
            user_email = user.email
            if self.cleaned_data.get('email')!=user_email:
                if RegistrationProfile.objects(
                    email__iexact=self.cleaned_data['email']):
                    print "Ya existe una cuenta con ese email."
                    raise forms.ValidationError(
                        _(u'Ya existe una cuenta con ese email.'))

        return self.cleaned_data

    def save(self ,user_edit,current_user):
        """
        Create the new ``User`` and ``RegistrationProfile``, and
        returns the ``User``.

        """
        new_user = RegistrationProfile.create_inactive_user(username=self.cleaned_data['username'],
                                                            password=self.cleaned_data['password1'],
                                                            email=self.cleaned_data['email'],
                                                            user_edit=user_edit,
                                                            name=self.cleaned_data['name'],
                                                            current_user=current_user)
        
                                                            
        return new_user

class RegistrationFormStp2(forms.Form):

    street_num = forms.CharField(max_length=90, required=False, widget=forms.TextInput(attrs={'placeholder':'Calle y numero', 'class':'bg-gray required', 'data-type':'text'}), label=(u'Calle y numero'), initial='Dirección')
    colony = forms.CharField(max_length=90, required=False, widget=forms.TextInput(attrs={'placeholder':'Colonia', 'class':'bg-gray required', 'data-type':'text'}), label=(u'Colonia'))
    deleg_mun = forms.CharField(max_length=90, required=False, widget=forms.TextInput(attrs={'placeholder':'Delegacion/munucipio', 'class':'bg-gray required', 'data-type':'text'}), label=(u'Delegacion/munucipio'))
    zc = forms.CharField(max_length=5, required=False, widget=forms.TextInput(attrs={'placeholder':'Código postal', 'class':'bg-gray required', 'data-type':'text', 'onkeypress':'return onlyNumbersDano(event)', 'maxlength':'5'}), label=(u'Codigo postal'))
    city = forms.CharField(max_length=90, required=False, widget=forms.TextInput(attrs={'placeholder':'Ciudad', 'class':'bg-gray required', 'data-type':'text'}), label=(u'Ciudad'))
    state = forms.CharField(max_length=90, required=False, widget=forms.TextInput(attrs={'placeholder':'Estado', 'class':'bg-gray required', 'data-type':'text'}), label=(u'Estado'))
    country = forms.CharField(max_length=90, required=False, widget=forms.TextInput(attrs={'placeholder':'País', 'class':'bg-gray required', 'data-type':'text'}), label=(u'País'))
    
    about_me = forms.CharField(max_length=70, widget=forms.Textarea(attrs={'placeholder':'Escribe algo sobre ti máximo 70 caracteres.', 'class':'bg-gray required', 'data-type':'text'}),required=False)
    
    stp1_id = forms.CharField(widget=forms.HiddenInput(attrs={'ng-model':'form_id','value':'{[form_id="form_id_12"]}'}),required=False)
    nxt_stp_id = forms.CharField(widget=forms.HiddenInput(attrs={'ng-model':'kamvia_next_id', 'value':'{[kamvia_next_id]}'}),required=False)

    def save(self,profile_id,user_edit):

        address = Address(street_num=self.cleaned_data['street_num'],
                                 colony=self.cleaned_data['colony'],
                                 deleg_mun=self.cleaned_data['deleg_mun'],
                                 zc=self.cleaned_data['zc'],
                                 city=self.cleaned_data['city'],
                                 state=self.cleaned_data['state'],
                                 country=self.cleaned_data['country'],
                                 about_me=self.cleaned_data['about_me'])

        profile_nivel_2 = RegistrationProfile.register_profile_step_2(profile_id,address,user_edit);

        return profile_nivel_2

class FormInviteFriends(forms.Form):
    

user/templates/activate.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

		<title>activate</title>
		<meta name="description" content="" />
		<meta name="author" content="Joselo" />

		<meta name="viewport" content="width=device-width; initial-scale=1.0" />

		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
	</head>

	<body>
		<div>
			<header>
				<h1>Activacion de cuenta</h1>
			</header>
			<nav>
				<p>
					<a href="/">Home</a>
				</p>
				<p>
					<a href="/contact">Contact</a>
				</p>
			</nav>

			<div>
				{{ account.username }}TU CUENTA HA SIDO ACTIVADA!!!
			</div>

			<footer>
				<p>
					&copy; Copyright  by Kamvia.mx
				</p>
			</footer>
		</div>
	</body>
</html>

user/templates/base_new_password.html
<!DOCTYPE html>
<html ng-app="kamviaApp">
	<head >
		<meta charset="utf-8" />

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

		<title>{% block title%}{% endblock %}</title>
		<meta name="description" content="" />
		<meta name="author" content="Joselo" />
        <!--
		<meta name="viewport" content="width=device-width; initial-scale=1.0" />
        -->
		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" href="/apple-touch-icon.png" />

		<!-- Font Family -->
    	<link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans:bolditalic,300italic,400,300,bold'>

		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/basic.css" />
		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/main.css" />
		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/jquery.fancybox.css?v=2.1.5" media="screen" />
		<!-- script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script -->
		<script src="{{STATIC_URL}}js/jquery-1.9.0.js"></script>
		<script type="text/javascript" src="{{STATIC_URL}}js/jquery.fancybox.js?v=2.1.5"></script>
		<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"></script> 
		<script src="{{STATIC_URL}}js/register.js"></script>
		<script src="{{STATIC_URL}}js/module.js"></script>
		<script src="{{STATIC_URL}}js/script.js"></script>
	</head>

	<body class="bg-gray">
<div id="header" class="bg-blue header-regiter-content">
      <div class="step-bar-regiter step-bar bg-blue">
        <ul>
          {% block steps %}{% endblock %}
        </ul>
      </div>
    </div>

		<div id="content" class="bg-gray left">
			<div class="template-content">
			<!-- Template content -->
				<div class="register-container">
        <!--  Register-container  -->
					{% block sub_title %}{% endblock %}

					<div class="content-external-form">
						{% block image_upload %}{% endblock %}
						{% block invite %}{% endblock %}
						<form id="register-form" action="/account/change_pass/" method="post" enctype="multipart/form-data">
							{% block container %}{% endblock %}
							{% csrf_token %}
							{% block ctrls_content %}{% endblock %}
						</form>

						<div class="clear"></div>
					</div>
				<!-- End Register-container  -->
				</div>
			<!-- End Template content -->
			</div>
		</div>
		<script>
      $(function(){
      	$('#id_key_salt').val('{{ salt }}')
      	{% if request.method == 'POST' %}
			$.fancybox.open('{{form.non_field_errors}}{{form.password.errors}}');
		{% endif %}
      });
    </script>
	</body>
</html>

user/templates/base_registration.html
<!DOCTYPE html>
<html ng-app="kamviaApp">
	<head >
		<meta charset="utf-8" />

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

		<title>{% block title%}{% endblock %}</title>
		<meta name="description" content="" />
		<meta name="author" content="Joselo" />
        <!--
		<meta name="viewport" content="width=device-width; initial-scale=1.0" />
        -->
		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" href="/apple-touch-icon.png" />

		<!-- Font Family -->
    	<link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans:bolditalic,300italic,400,300,bold'>

		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/basic.css" />
		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/main.css" />
		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/jquery.fancybox.css?v=2.1.5" media="screen" />
		<!-- script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script -->
		<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
		<script type="text/javascript" src="{{STATIC_URL}}js/jquery.fancybox.js?v=2.1.5"></script>
		<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"></script> 
		<script src="{{STATIC_URL}}js/register.js"></script>
		<script src="{{STATIC_URL}}js/module.js"></script>
		<script src="{{STATIC_URL}}js/script.js"></script>
		<script src="http://connect.facebook.net/en_US/all.js"></script>
	</head>

	<body class="bg-gray">
		<!-- Facebook content -->
		<div id="fb-root"></div>
		<!-- Facebook JS -->
		
{% if user_id %}
{% include 'header_menu.html' %}

{% else %}
<div id="header" class="bg-blue header-regiter-content">
      <div class="step-bar-regiter step-bar bg-blue">
        <ul>
          {% block steps %}{% endblock %}
        </ul>
      </div>
    </div>
{% endif %}
		

		<div id="content" class="bg-gray left">
			<div class="template-content">
			<!-- Template content -->
				<div class="register-container">
        <!--  Register-container  -->
					{% block sub_title %}{% endblock %}

					<div class="content-external-form">
						{% block image_upload %}{% endblock %}
						{% block invite %}{% endblock %}
						<form id="register-form" ng-controller="RegisterCtrl" action="{[kamvia_action]}" method="post" enctype="multipart/form-data">
							{% block container %}{% endblock %}
							{% csrf_token %}
							{% block ctrls_content %}{% endblock %}
						</form>

						<div class="clear"></div>
					</div>
				<!-- End Register-container  -->
				</div>
			<!-- End Template content -->
			</div>

			<footer>
				<p></p>
			</footer>
		</div>
		<script>

      $(function(){
      	{% if request.method == 'POST' %}
      		showFancyBoxMessage('<b>ERROR</b>','{{form.non_field_errors}}{{form.username.error}}{{form.email.error}}{{form.password.error}}{{form.tos.error}}',false);
			//$.fancybox.open('{{form.non_field_errors}}{{form.username.error}}{{form.email.error}}{{form.password.error}}{{form.tos.error}}');
		{% endif %}
      });
    </script>
	</body>
</html>

user/templates/registration_basic.html
{% extends 'base_registration.html' %}

{% block steps %}
	<li class="gray text-center active">1</li>
	{%if edit%}
		<li class="gray text-center">2</li>
		<li class="gray text-center">3</li>
	{%endif%}
{% endblock%}
	
{% block sub_title %}
	<h1 class="text-center">{%if user_id%}Editar{%endif%} Información Básica</h1>
	<p class="text-center">
		Éste es el primer paso de tres y el único obligatorio, puedes empezar<br/>
		a intercambiar al instante, pero te recomendamos completar los demás para tener una mejor experiencia.
	</p>
{% endblock%}

{% block container %}
	<div class="regiter-info-content regiter-info-2-content">
		
		<ul>
			<li class="left">
				{% for field in form %}
					{% if field.name != 'tos'%}
						{{ field }}
					{% endif%}
				{% endfor %}
				 
			<li class="left">
				<p class="register-description">{{ form.name.label_tag }}</p>
				<p class="register-description">{{ form.username.label_tag }}</p>
				<p class="register-description">{{ form.email.label_tag }}</p>
				<p class="register-description">{{ form.password1.label_tag }}</p>
				<p class="register-description">{{ form.password2.label_tag }}</p>
			</li>

		</ul>
		{% if user_id %}
			<input id="id_tos" type="checkbox" style="display:none;" name="tos" checked>

		{% else %}
			{{form.tos}}
		<p style="float:left;!important font-size: 13px !important;font-style: italic !important;font-weight: lighter !important; padding: 5px 0 14px; margin-left:10px;">
			He leído y estoy de acuerdo con los <a href="/tos/" target="_blank" style="color:#666666; font-size:bold;">TÉRMINOS Y CONDICIONES</a><br>
		</p>
		{% endif %}
			</li>				
		<div class="clear"></div>
	</div>

	<!-- Submit ctrls -->
    
        {%if edit %}
	        <div id="user-register-ctrl" class="register-ctrols">
	      		<div class="register-ctrols-content">
	      			<input type="submit" class="left active" value="{%if user_id%}Editar{%else%}Comenzar ya{%endif%}" ng-mouseover="startKamvia()" id="start"/>
	        		<input id="register-next-step" type="submit" class="left active" value="{%if user_id%}Siguiente{%else%}Paso siguiente{%endif%}" ng-mouseover="nextKamvia()"/>
	        	</div>
    		</div>
        {%else%}
        	<div id="user-register-ctrl" class="register-ctrols">

		        <input type="submit" class="left active" value="{%if user_id%}Editar{%else%}Comenzar ya{%endif%}" ng-mouseover="startKamvia()" id="start"/>
		      
    		</div>
        {%endif%}
      
    	{% if user_id %}
		<script type="text/javascript">
		$(document).ready(function() {
					$("input[name='name']").val('{{ user_name }}');
					$("input[name='username']").val('{{ user_username }}');
					$("input[name='email']").val('{{ user_mail }}');
					$("input[name='user']").val('{{ user_id }}');
				});
		</script>
		{% endif %}
{% endblock %}

user/templates/registration_trust.html
{% extends 'base_registration.html' %}

{% block steps %}
  <li class="gray text-center">1</li>
  <li class="gray text-center active">2</li>
  <li class="gray text-center">3</li>
{% endblock%}

{% block sub_title %}
{% if user_id %}
  <h1 class="text-center">Editar Información de confianza y afinidad</h1>
{% else %}
  <h1 class="text-center">Informacíon de confianza y afinidad</h1>
{% endif %}
  
  <p class="text-center">
      Te recomendamos tener esta información para que sea más fácil<br/>
      que la gente intercambie algo contigo.
  </p>
{% endblock %}

{% block image_upload %}
  <div id="regiter-upload-image" class="left">
    <form id="upload" action="/account/picture/" method="POST" enctype="multipart/form-data">
      <input type="hidden" id="MAX_FILE_SIZE" name="MAX_FILE_SIZE" value="300000" />
      <div class="image-preview">
          <p class="text-left">Haz click y sube una foto</p>
          <div id="filedrag">or drop files here</div>
          <input type="file" id="fileselect" name="files" multiple="multiple" class="transparent" />
      </div>

      <div id="submitbutton">
        <button type="submit">Upload Files</button>
      </div>
    </form>

    <div id="progress"></div>

    <div id="messages"></div>
  </div>

  <script src="{{STATIC_URL}}js/file-upload.js"></script>
{% endblock %}

{% block container %}
  <div class="regiter-info-content regiter-info-3-content left" style="width: 430px;">
    <ul>
      <li class="left">
        {{ form.street_num }}
        {{ form.colony }}
        {{ form.deleg_mun }}
        {{ form.zc }}
        {{ form.city }}
        {{ form.state }}
        {{ form.country }}
      </li>
      <li>
        {{ form.about_me }}
        {{ form.stp1_id }}
        {{ form.nxt_stp_id }}
      </li>
    </ul>
        
    <div class="clear"></div>
  </div>

  <div class="clear"></div>
  <!-- Submit ctrls -->
  <div id="user-register-ctrl" class="register-ctrols">
    <div class="register-ctrols-content">
      <input type="submit" class="left active inactive" value="Comenzar ya" ng-mouseover="startKamvia()"/>
      <input type="submit" class="left active inactive" value="Paso siguiente" ng-mouseover="nextKamvia()"/>
    </div>
  </div>
    {% if user_id %}
    <script type="text/javascript">
    $(document).ready(function() {
          $('#id_street_num').val('{{ street_num }}');
          $('#id_colony').val('{{ colony }}');
          $('#id_deleg_mun').val('{{ deleg_mun }}');
          $('#id_zc').val('{{ zc }}');
          $('#id_city').val('{{ city }}');
          $('#id_state').val('{{ state }}');
          $('#id_country').val('{{ country }}')
          $('#id_about_me').val('{{ about_me }}')
        });
    </script>
    {% endif %}
{% endblock %}